### ISSUE TITLE
iOS 10 NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

### ISSUE THREAD

**Issue by jiangweike** [xlsd/SDWebView#1]
图片加载失败

-----------image-preview:https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1491412460286&di=703c05458243b0635aa4d28f0f11e855&imgtype=0&src=http%3A%2F%2Fimg1.lotour.net%2FInspiration%2F2017%2F0219%2F20170219065643386969029_910.jpg
2017-04-20 17:25:22.944189+0800 SDWebViewDemo[78813:3835329] [] nw_coretls_read_one_record tls_handshake_process: [-9824]
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

**Comment by xlsd** [comment]
我测试的时候并没有发现你说的不能预览的问题。有什么更具体的错误码？我看下。。。也可以联系我413890968@qq.com
