### ISSUE TITLE
重复下载图片

### ISSUE THREAD

**Issue by xushuduo** [xlsd/SDWebView#2]
作者有没有发现，网页加载过一次后，用SDPhotoBrowserd浏览又下载了一次，用户体验0

**Comment by xlsd** [comment]
你提的这个问题是的，其实要加载webView上的图片，比较便捷的方式，就是拿到所点击图片的 URL，然后使用原生的控件加载出来。因为图片资源原本就在远端的H5界面上，但是本库用了缓存，所以保证本地只需加载一次。而且目前来说，H5的图片预览大部分都是这个模式，你有没有好的建议？
