### ISSUE TITLE
无语

### ISSUE THREAD

**Issue by Vincent-20481** [xlsd/SDWebView#3]
URL输入百度都打不开

**Comment by xlsd** [comment]
你打开ATS了吗？需要在infoplist文件中打开ATS设置才行。。。。真的，不骗你。大概就是你没开ATS

**Comment by Vincent-20481** [comment]
兄弟,我下载你Demo里面的图片可是网络请求的you,后来请求不到加了ATS 表示不行才反馈的you,你自己试试

**Comment by xlsd** [comment]
请尝试以下提供的方法：
步骤1：
![snip20170606_2](https://user-images.githubusercontent.com/18232314/26835708-7d6234de-4b0b-11e7-90de-e5b17ab12e2a.png)

步骤2：
![snip20170606_1](https://user-images.githubusercontent.com/18232314/26835746-91105402-4b0b-11e7-963d-54549c8cbe74.png)
![snip20170606_3](https://user-images.githubusercontent.com/18232314/26835837-b62e343e-4b0b-11e7-8b14-e2b8a99ca390.png)

看下能不能打开百度，因为我试了是可以的，我猜测还是ATS的原因
