### ISSUE TITLE
输入url地址后无法弹出图片浏览器，只能加载本地的html

### ISSUE THREAD

**Issue by apiapia** [xlsd/SDWebView#6]
SDWebView *webView = [[SDWebView alloc] initWithFrame:self.view.bounds];
    //[webView loadLocalHTMLWithFileName:@"source"];
    
    
    //  Example like this, you need set ATS allow load Yes.
      [webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://feed.baidu.com/feed/data/wise/landingpage?s_type=news&dsp=wise&nid=15240162467347623609&n_type=0&p_from=-1#viewportType=virtual&paddingTop=54&pageType=&pageInfo="]]];
    
    [self.view addSubview:webView];

然后点击网页上的图片无法自动弹出，是否还要在哪里写OC与JS的互动呢？

**Comment by giveMeHug** [comment]
经过排查，是因为百度的内嵌图片的方式是在iframe中内嵌引入的，所以SDWebview的js其实并没有拿大图片。这种前端的方式SDWebview暂时不支持，我在Demo中已经更换了SDwebView支持的场景，也是大部分情况下适用的场景，请再次查看。

**Comment by xlsd** [comment]
经过排查，是因为百度的内嵌图片的方式是在iframe中内嵌引入的，所以SDWebview的js其实并没有拿大图片。这种前端的方式SDWebview暂时不支持，我在Demo中已经更换了SDwebView支持的场景，也是大部分情况下适用的场景，请再次查看。 @apiapia
