### ISSUE TITLE
您好，无法吊起图片预览功能

### ISSUE THREAD

**Issue by niuxinhuai** [xlsd/SDWebView#7]
为什么加载我从网上拿下来的html连接的时候，无法预览图片呢。 @"https://promotion-dev.beichoo.com/beichoo_app/article/index.html?user_id=&token=&article_id=wx-http%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzAwMDE1MDE1MQ%3D%3D%26mid%3D2455023623%26idx%3D5%26sn%3Daef6ef9462d38ffab8bdb81d2c551a92%26scene%3D0"这个是链接，麻烦有时间看下

**Comment by xlsd** [comment]
我知道原因了，这个图片实际上是不在当前这个页面，是在iframe内嵌的，这个是SDWebView框架解决不了的，不过，这也不是没有办法，你需要和web开发人员商讨解决方案，比如：让web开发人员提供一个js方法返回一个图片地址的数组，然后使用SDWebView调用该js方法，获取到数组即可。
